#!/usr/bin/env python3
"""Fetch the full UMLS Semantic Network (all semantic types + tree numbers) and
render it as a hierarchical tree.

Writes:
  mapping/semantic_types.yaml        - the reference data (tui, name, tree, def)
  mapping/semantic_network_tree.md   - the tree, annotated with where each GEM
                                       dimension axis currently *derives* to
                                       (the modal semantic type of its mapped
                                       values), so untyped axes are visible.

Use this to decide which dimension axes have a faithful UMLS semantic type and
which are untyped (unmapped). Requires UMLS_API_KEY (env or .envrc).

Usage:
    python3 mapping/fetch_semantic_network.py
    python3 mapping/fetch_semantic_network.py --max 220   # TUI scan upper bound
"""
from __future__ import annotations

import argparse
import re
from collections import Counter, defaultdict

import yaml

from forome.gem.umls import build_umls_crosswalk as H
from forome.gem.umls import adjudicate_ui as UI  # reuse api_key()
from forome.gem.umls.uts_client import UTSClient
from forome.gem.umls._paths import DATA_DIR

TYPES_YAML = DATA_DIR / "semantic_types.yaml"
TREE_MD = DATA_DIR / "semantic_network_tree.md"
CROSSWALK = DATA_DIR / "umls_crosswalk.yaml"


def tree_sort_key(tn: str):
    key = []
    for p in (tn or "").split("."):
        m = re.match(r"([A-Za-z]*)(\d+)", p)
        key.append((m.group(1), int(m.group(2))) if m else ("", 0))
    return key


def axis_derivations() -> dict:
    """semantic-type name -> [dimensions whose mapped values are modally that type]."""
    if not CROSSWALK.is_file():
        return {}
    doc = yaml.safe_load(CROSSWALK.read_text())
    per = defaultdict(Counter)
    for e in doc["entries"]:
        if e["kind"] in ("value", "common_value") and e["status"] == "mapped":
            for st in (e.get("semantic_types") or []):
                per[e["dimension"]][st] += 1
    name_to_axes = defaultdict(list)
    for dim, cnt in per.items():
        if cnt:
            name_to_axes[cnt.most_common(1)[0][0]].append(dim)
    return name_to_axes


def fetch_all(client, upper: int) -> list:
    types = []
    for n in range(1, upper + 1):
        st = client.get_semantic_type(f"T{n:03d}")
        if st and st.get("tree_number"):
            types.append(st)
    types.sort(key=lambda s: tree_sort_key(s["tree_number"]))
    return types


def _is_type(s) -> bool:
    return (s["tree_number"] or "").startswith(("A", "B"))


def render_tree(types: list, derivations: dict) -> str:
    sem = [s for s in types if _is_type(s)]          # semantic TYPES (A/B)
    rel = [s for s in types if not _is_type(s)]       # relations (R)
    lines = ["# UMLS Semantic Network — semantic types tree",
             "",
             f"_{len(sem)} semantic types (plus {len(rel)} relations, listed at "
             "the end). Generated by mapping/fetch_semantic_network.py from the "
             "live UTS API._",
             "",
             "Dimension **axes** map to a semantic **type** (A/B branches below); "
             "dimension **values** map to Metathesaurus concepts. GEM axes are "
             "annotated at the type their mapped values currently *derive* to "
             "(modal). Axes with no typed values are untyped/unmapped candidates "
             "(e.g. `target_type`, `resolution`, `credibility`, "
             "`variant_ascertainment`).",
             "", "## Semantic types", "", "```"]
    for s in sem:
        depth = len((s["tree_number"] or "").split("."))
        indent = "  " * (depth - 1)
        axes = derivations.get(s["name"])
        tag = ("   <== GEM axis: " + ", ".join(sorted(axes))) if axes else ""
        lines.append(f"{indent}{s['tree_number']:<12} {s['name']}  ({s['tui']}){tag}")
    lines += ["```", "", "## Relations (for reference)", "", "```"]
    for s in rel:
        depth = len((s["tree_number"] or "").split("."))
        lines.append(f"{'  ' * (depth - 1)}{s['tree_number']:<10} {s['name']}  ({s['tui']})")
    lines.append("```")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max", type=int, default=220, help="TUI scan upper bound")
    args = ap.parse_args(argv)

    key = UI.api_key()
    if not key:
        print("ERROR: no UMLS_API_KEY (env or .envrc).")
        return 1
    client = UTSClient(key, cache_dir=H.CACHE_DIR)
    print(f"Fetching semantic types T001..T{args.max:03d} (cached after first run)...")
    types = fetch_all(client, args.max)
    TYPES_YAML.write_text(yaml.safe_dump(
        {"count": len(types), "source": "UMLS Semantic Network (UTS API)",
         "types": types}, sort_keys=False, allow_unicode=True, width=200))
    tree = render_tree(types, axis_derivations())
    TREE_MD.write_text(tree)
    print(f"Wrote {TYPES_YAML.name} ({len(types)} types) and {TREE_MD.name}.")
    # top-level summary to stdout
    tops = [s for s in types if len((s["tree_number"] or "").split(".")) <= 2]
    print("\nTop-level branches:")
    for s in tops:
        print(f"  {s['tree_number']:<8} {s['name']} ({s['tui']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
